export const mockLeads = [
  {
    id: 1,
    orgName: "Impact Seed (Connector)",
    contactName: "Jasmine",
    contactTitle: "",
    contactInitials: "JA",
    stage: "Engaged",
    priority: "High",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Family Office"],
    region: "Australia",
    category: "Philanthropy",
    comments: "They have a fund and family offices want it deployed into 1st nations projects. Now raising 2nd $10M fund. COuld be impa",
    action: "Package something tailored to them, board advisor + equity investment + philanthrophy"
  },
  {
    id: 2,
    orgName: "Spinifex Foundation",
    contactName: "Sophie Chamberlain",
    contactTitle: "",
    contactInitials: "SC",
    stage: "Engaged",
    priority: "High",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Direct Outreach"],
    region: "Australia",
    category: "Philanthropy",
    comments: "Highly engaged. Notes a lack of aligned vehicles for their corpus. Believes if she invests, her network will follow (FOMO)",
    action: "Give her a few more days to consult siblings post-holidays, then follow up."
  },
  {
    id: 3,
    orgName: "Lotterywest",
    contactName: "Lorna Pritchard",
    contactTitle: "",
    contactInitials: "LP",
    stage: "Contacted",
    priority: "Medium",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Shared Lead"],
    region: "Australia",
    category: "Philanthropy",
    comments: "Clarified they can only invest in the philanthropic fund (Fund 1), not the commercial/equity fund.",
    action: "Ollie drafting a scoping/operational document outlining structure and partnership model to send this week."
  },
  {
    id: 4,
    orgName: "WWF",
    contactName: "Monica Richter",
    contactTitle: "",
    contactInitials: "MR",
    stage: "Engaged",
    priority: "Critical",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Direct Outreach"],
    region: "Australia",
    category: "Philanthropy",
    comments: "Bit immediately on industrial decarb angle. Releasing a white paper soon. Massive brand-halo opportunity for Biome.",
    action: "Follow-up call on Monday to push broader partnership conversation and propose an online workshop."
  },
  {
    id: 5,
    orgName: "Bennett Family Office",
    contactName: "Stuart Anste / Paul Bennett / Todd",
    contactTitle: "",
    contactInitials: "SA",
    stage: "New",
    priority: "Medium",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Warm Intro"],
    region: "Australia",
    category: "Philanthropy",
    comments: "Initial walls hit, but new entry points identified. Paul Bennett is the target for nature; Todd is looking for a full-ti",
    action: "Ollie to contact Stuart Anste (Lead, Nature Positive). Nicole to leverage personal connection for an off-the-record chat"
  },
  {
    id: 6,
    orgName: "Sydney HNWI Network",
    contactName: "Nicole's Contact",
    contactTitle: "",
    contactInitials: "NC",
    stage: "Awaiting Response",
    priority: "Medium",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Warm Intro"],
    region: "Australia",
    category: "Philanthropy",
    comments: "Contact is currently 'hunting through the pack' to identify quiet HNWIs in Sydney passionate about nature.",
    action: "Await names/introductions from contact."
  },
  {
    id: 7,
    orgName: "AEGN",
    contactName: "Claire O'Rourke",
    contactTitle: "",
    contactInitials: "CO",
    stage: "Contacted",
    priority: "Medium",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Cold Outreach"],
    region: "Australia",
    category: "Philanthropy",
    comments: "Australian Environmental Grantmakers Network. Outreach sent.",
    action: "Nicole to follow up if no response is received in the coming days."
  },
  {
    id: 8,
    orgName: "Minderoo",
    contactName: "Kirsten Stevenson",
    contactTitle: "",
    contactInitials: "KS",
    stage: "New",
    priority: "Medium",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Direct Outreach"],
    region: "Australia",
    category: "Philanthropy",
    comments: "",
    action: ""
  },
  {
    id: 9,
    orgName: "Clough Group / Oceans Institute",
    contactName: "Jock Clough",
    contactTitle: "",
    contactInitials: "JC",
    stage: "Parked",
    priority: "Low",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Direct Outreach"],
    region: "Australia",
    category: "Philanthropy",
    comments: "Met with Nicole. Active in marine (recently deployed $3M) but prefers direct project investment over funds.",
    action: "PARKED (for now): Re-engage once we have a specific, packaged marine project (kelp, mangroves, coral)."
  },
  {
    id: 10,
    orgName: "HNWI",
    contactName: "Alex Burt",
    contactTitle: "",
    contactInitials: "AB",
    stage: "New",
    priority: "Medium",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Warm Intro"],
    region: "Australia",
    category: "Philanthropy",
    comments: "Need to think of strategy as cold outreach",
    action: "Talking to Peter Klinken about intro; Peter will reconnect on the WA+ focus and then Nicole can pick up the Biome opport"
  },
  {
    id: 11,
    orgName: "HNWI",
    contactName: "Leonie Baldock",
    contactTitle: "",
    contactInitials: "LB",
    stage: "Contacted",
    priority: "Medium",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Cold Outreach"],
    region: "Australia",
    category: "Philanthropy",
    comments: "Need to think of strategy as cold outreach",
    action: "Nicole emailed Leonie on 11/11 with request to meet"
  },
  {
    id: 12,
    orgName: "Murdoch University",
    contactName: "Professor Andrew Deeks",
    contactTitle: "",
    contactInitials: "PD",
    stage: "Contacted",
    priority: "Medium",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Shared Lead"],
    region: "Australia",
    category: "Philanthropy",
    comments: "NIc knows but do they have funds? ",
    action: "Nicole emailed Andrew on 11/11 with request for meeting"
  },
  {
    id: 13,
    orgName: "Paul Ramsay Foundation",
    contactName: "Alex Martin",
    contactTitle: "",
    contactInitials: "AM",
    stage: "Closed",
    priority: "Low",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Direct Outreach"],
    region: "Australia",
    category: "Philanthropy",
    comments: "We have decided this is not for us. The scope of the fund is outside the remit of our concessional funding – which has",
    action: "Nicole emailed 13/11 with request for a meeting.  Model considered by Alex Burt and they have passed as it does not dire"
  },
  {
    id: 14,
    orgName: "Stan Perron Charitable Trust",
    contactName: "TBC",
    contactTitle: "",
    contactInitials: "??",
    stage: "New",
    priority: "Low",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Direct Outreach"],
    region: "Australia",
    category: "Philanthropy",
    comments: "Nic to do some digging",
    action: "only interested in health projects"
  },
  {
    id: 15,
    orgName: "Clough Engineering",
    contactName: "Jock Clough (Sam)",
    contactTitle: "",
    contactInitials: "J(",
    stage: "New",
    priority: "Low",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Foundation"],
    region: "Australia",
    category: "Philanthropy",
    comments: "I’ve had the opportunity to review everything with Jock, and unfortunately it falls outside the scope of what the Jock C",
    action: "Had call, 25th Nov, only interested in Marine, 100% rates Luke, asked luke for shark bay opp and one other, could be goo"
  },
  {
    id: 16,
    orgName: "H-U",
    contactName: "Adrian Fini",
    contactTitle: "",
    contactInitials: "AF",
    stage: "Contacted",
    priority: "Medium",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Direct Outreach"],
    region: "Australia",
    category: "Philanthropy",
    comments: "Michelle: Due to our current commitments we don't have the bandwidth to invest or get involved however we'll definitel",
    action: "Nicole emailed Adrian on 11/11 with request for meeting; Adrian currently overseas and will be in touch to make a time w"
  },
  {
    id: 17,
    orgName: "Poynton Partners",
    contactName: "John Poynton",
    contactTitle: "",
    contactInitials: "JP",
    stage: "Contacted",
    priority: "Medium",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Direct Outreach"],
    region: "Australia",
    category: "Philanthropy",
    comments: "Nic follow-up chat",
    action: "Nicole emailed John on 11/11 with request for meeting; he is considering the proposal and will be in touch soon to discu"
  },
  {
    id: 18,
    orgName: "The Feilman Foundation",
    contactName: "Jan Stewart",
    contactTitle: "",
    contactInitials: "JS",
    stage: "Contacted",
    priority: "Medium",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "philanthropy",
    tags: ["Warm Intro"],
    region: "Australia",
    category: "Philanthropy",
    comments: "Nicole to investigate",
    action: "Nicole emailed Jan on 11/11 to request meeting- preliminary feedback from Jan that a contribution from Fielman- Jan will"
  },
  {
    id: 19,
    orgName: "Impact Seed",
    contactName: "TBC",
    contactTitle: "",
    contactInitials: "??",
    stage: "Contacted",
    priority: "Medium",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "investor",
    tags: ["Shared Lead"],
    region: "Australia",
    category: "Investors",
    comments: "Great alignment on many fronts",
    action: "Waiting on follow-up to go into more detail on their follow-on contacts"
  },
  {
    id: 20,
    orgName: "WA Treasury Corporation",
    contactName: "Kaylean",
    contactTitle: "",
    contactInitials: "KA",
    stage: "Proposal Sent",
    priority: "Medium",
    ticketSize: "A$TBC",
    nextFollowUp: "",
    lastContact: "",
    type: "investor",
    tags: ["Government"],
    region: "Australia",
    category: "Investors",
    comments: "Invests on behalf of the state. Nicole pitched them on Biome being set up for institutional investment.",
    action: "Wants to know more about Biome 3.0, briefing offered"
  },
  {
    id: 21,
    orgName: "WA State Government",
    contactName: "James Yuen",
    contactTitle: "",
    contactInitials: "JY",
    stage: "New",
    priority: "Critical",
    ticketSize: "A$~$5M+",
    nextFollowUp: "",
    lastContact: "",
    type: "investor",
    tags: ["Government"],
    region: "Australia",
    category: "Investors",
    comments: "Precedent exists for state backing new VC funds (e.g., $200k for ManCo fees + $5M into the fund).",
    action: "Nicole to refine the pitch and approach the relevant department for similar venture/innovation backing."
  },
  {
    id: 22,
    orgName: "Aware Super",
    contactName: "Tim Channerand",
    contactTitle: "",
    contactInitials: "TC",
    stage: "New",
    priority: "Medium",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "investor",
    tags: ["Direct Outreach"],
    region: "Australia",
    category: "Investors",
    comments: "",
    action: "Nic to check"
  },
  {
    id: 23,
    orgName: "Curtin Angel Syndicate",
    contactName: "Larry Lopez",
    contactTitle: "",
    contactInitials: "LL",
    stage: "Contacted",
    priority: "Medium",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "investor",
    tags: ["Direct Outreach"],
    region: "Australia",
    category: "Investors",
    comments: "",
    action: "Had said yes but never confirmed date, will chase"
  },
  {
    id: 24,
    orgName: "Perth Angels",
    contactName: "Wilson",
    contactTitle: "",
    contactInitials: "WI",
    stage: "Engaged",
    priority: "High",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "investor",
    tags: ["Warm Intro"],
    region: "Australia",
    category: "Investors",
    comments: "Keen to talk and intro us to VDK (below)",
    action: "Will let us know feedback"
  },
  {
    id: 25,
    orgName: "VDK Ventures",
    contactName: "TBC",
    contactTitle: "",
    contactInitials: "??",
    stage: "New",
    priority: "Medium",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "investor",
    tags: ["Warm Intro"],
    region: "Australia",
    category: "Investors",
    comments: "Intro from Perth Ventures",
    action: ""
  },
  {
    id: 26,
    orgName: "Clean Energy Finance Corporation",
    contactName: "Heech Sul (Malcolm Thornton?)",
    contactTitle: "",
    contactInitials: "HT",
    stage: "New",
    priority: "Medium",
    ticketSize: "",
    nextFollowUp: "",
    lastContact: "",
    type: "investor",
    tags: ["Direct Outreach"],
    region: "Australia",
    category: "Investors",
    comments: "They have a head of natural capital division, Nic meeting",
    action: ""
  },
  {
    id: 27,
    orgName: "Deloitte",
    contactName: "Matt Judkins",
    contactTitle: "",
    contactInitials: "MJ",
    stage: "Meeting Set",
    priority: "Critical",
    ticketSize: "TBC",
    nextFollowUp: "",
    lastContact: "",
    type: "investor",
    tags: ["Shared Lead"],
    region: "Australia",
    category: "Investors",
    comments: "Have already set up their own ACCU projects. Strong potential as a cornerstone commercial investor or ManCo equity partn",
    action: "In-person meeting scheduled for the 4th, Glen too; Nicole to loop back with Matt Judkins afterward."
  },
  {
    id: 28,
    orgName: "Rio Tinto",
    contactName: "Sarah, Amy, Declan, Jonty",
    contactTitle: "",
    contactInitials: "SA",
    stage: "New",
    priority: "Medium",
    ticketSize: "TBC",
    nextFollowUp: "",
    lastContact: "",
    type: "investor",
    tags: ["Warm Intro"],
    region: "Australia",
    category: "Investors",
    comments: "Nicole ran into Sarah and Amy at a dinner. Tamron advised re-engaging in the New Year.",
    action: "Nicole to ask Rohan for a warm re-intro for coffee with Sarah/Amy. Lorenzo to continue warming up Declan/Jonty."
  },
  {
    id: 29,
    orgName: "Woodside",
    contactName: "Julie Fallon / Ben Wyatt",
    contactTitle: "",
    contactInitials: "JF",
    stage: "New",
    priority: "Medium",
    ticketSize: "TBC",
    nextFollowUp: "",
    lastContact: "",
    type: "investor",
    tags: ["Shared Lead"],
    region: "Australia",
    category: "Investors",
    comments: "Need a top-down and bottom-up approach.",
    action: "Nicole to piggyback on her husband\'s meeting with Julie Fallon. Glen to try Ben Wyatt again."
  },
  {
    id: 30,
    orgName: "BHP, Alcoa, Wesfarmers",
    contactName: "Luke Bailey / Owen (Connectors)",
    contactTitle: "",
    contactInitials: "LB",
    stage: "Parked",
    priority: "Medium",
    ticketSize: "TBC",
    nextFollowUp: "",
    lastContact: "",
    type: "investor",
    tags: ["Shared Lead"],
    region: "Australia",
    category: "Investors",
    comments: "Luke and Owen have deep industry relationships with the major miners.",
    action: "Hold a call with Luke/Owen to formally ask them to open doors, potentially tied to formalizing their advisory roles."
  },
];

export const mockInteractions = [
  {
    id: 1,
    leadId: 2,
    date: "2025-03-15",
    type: "Call",
    summary: "Sophie consulting siblings post-holidays, very engaged",
    outcome: "Awaiting Response",
    followUpDate: "2025-03-22"
  },
  {
    id: 2,
    leadId: 4,
    date: "2025-03-10",
    type: "Call",
    summary: "Partnership conversation - industrial decarb angle resonated strongly",
    outcome: "Follow-up Required",
    followUpDate: "2025-03-17"
  },
  {
    id: 3,
    leadId: 20,
    date: "2025-03-04",
    type: "Meeting",
    summary: "In-person meeting with Matt Judkins, Glen attended",
    outcome: "Positive",
    followUpDate: "2025-03-11"
  },
  {
    id: 4,
    leadId: 21,
    date: "2025-02-28",
    type: "Email",
    summary: "Nicole ran into Sarah and Amy at dinner, re-engaging in New Year",
    outcome: "Warm Lead",
    followUpDate: "2025-03-10"
  },
  {
    id: 5,
    leadId: 8,
    date: "2025-03-01",
    type: "Email",
    summary: "Follow-up with Minderoo, Kirsten Stevenson",
    outcome: "Pending",
    followUpDate: "2025-03-15"
  },
  {
    id: 6,
    leadId: 16,
    date: "2024-12-09",
    type: "Meeting",
    summary: "Meeting with Adrian Fini at H-U offices",
    outcome: "Interested but no bandwidth currently",
    followUpDate: "2025-01-15"
  }
];

export const mockTeam = [
  {
    id: 1,
    name: "Nicole Sterling",
    email: "n.sterling@biome.com",
    role: "Lead",
    initials: "NS",
    avatarBg: "bg-primary-container"
  },
  {
    id: 2,
    name: "Glen Kelly",
    email: "g.kelly@biome.com",
    role: "Co-Lead",
    initials: "GK",
    avatarBg: "bg-secondary-fixed"
  },
  {
    id: 3,
    name: "Olly",
    email: "olly@biome.com",
    role: "Member",
    initials: "OL",
    avatarBg: "bg-tertiary-fixed"
  },
  {
    id: 4,
    name: "Lorenzo",
    email: "lorenzo@biome.com",
    role: "Member",
    initials: "LO",
    avatarBg: "bg-primary-fixed"
  }
];
